namespace: hello-dev
resources:
  - ../../base
namePrefix: dev-
commonLabels:
  env: dev
patches:
  - target:
      kind: Deployment
      name: hello-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: public.ecr.aws/docker/library/nginx:1.25-alpine
 