apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app.kubernetes.io/name: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-app
    spec:
      containers:
        - name: web
          image: nginx:alpine 
          ports:
            - containerPort: 8080
          #readinessProbe:
          #    httpGet: { path: /, port: 8080 }
          #livenessProbe:
          #httpGet: { path: /, port: 8080 }
